simulate_coverage.py:
 name: simulation
 looper_args: True
 arguments:
  "--sample_id" : sample_name
  "--chr" : chr
  "--start" : start
  "--end" : end
  "--number" : reads
 resources:
  default:
   file_size: "0"
   cores: "4"
   mem: "4000"
   h_vmem: "10G"
simulate_read_length.py:
 name: simulation
 looper_args: True
 arguments:
  "--sample_id" : sample_name
  "--chr" : chr
  "--start" : start
  "--end" : end
  "--number" : reads
  "--length" : length
 resources:
  default:
   file_size: "0"
   cores: "4"
   mem: "4000"
   h_vmem: "10G"
simulate_sequencing_errors.py:
 name: simulation
 looper_args: True
 arguments:
  "--sample_id" : sample_name
  "--chr" : chr
  "--start" : start
  "--end" : end
  "--error" : error
 resources:
  default:
   file_size: "0"
   cores: "4"
   mem: "4000"
   h_vmem: "10G"
simulate_CT_heterogeneity.py:
 name: simulation
 looper_args: True
 arguments:
  "--sample_id" : sample_name
  "--chr" : chr
  "--start" : start
  "--end" : end
 resources:
  default:
   file_size: "0"
   cores: "4"
   mem: "4000"
   h_vmem: "10G"
simulate_sample_purity.py:
 name: simulation
 looper_args: True
 arguments:
  "--sample_id" : sample_name
  "--chr" : chr
  "--start" : start
  "--end" : end
 resources:
  default:
   file_size: "0"
   cores: "4"
   mem: "4000"
   h_vmem: "10G"
simulate_ASM.py:
 name: simulation
 looper_args: True
 arguments:
  "--sample_id" : sample_name
  "--chr" : chr
  "--start" : start
  "--end" : end
 resources:
  default:
   file_size: "0"
   cores: "4"
   mem: "4000"
   h_vmem: "10G"
