metadata:
 sample_annotation: annotation_generator/sample_annotation.csv
 output_dir: /TL/deep/projects/work/mscherer/projects/heterogeneity/simulation/results/correct_simulation/negative_example/
 pipelines_dir: .
