calculate_heterogeneity_scores.py:
 name: heterogeneity
 looper_args: True
 arguments:
  "--sample_id" : sample_name
  "--bam_name" : bam_path
 resources:
  default:
   file_size: "0"
   cores: "6"
   mem: "80000"
   h_vmem: "120G"
