calculate_heterogeneity_scores.py:
 name: heterogeneity
 looper_args: True
 arguments:
  "--sample_id" : sample_name
  "--fastq_name" : fastq_path
 resources:
  default:
   file_size: "0"
   cores: "4"
   mem: "40000"
   h_vmem: "60G"
